Save current state of PR workflow

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -45,17 +45,13 @@ jobs:
         with:
           name: templateUrlMieRelease
           path: src/templateUrlMieRelease.txt
-          retention-days: 1
+          retention-days: 3
       - name: 'Upload Developer Deployment Artifact'
         uses: actions/upload-artifact@v2
         with:
           name: templateUrlMieDevelopment
           path: src/templateUrlMieDevelopment.txt
-          retention-days: 1
-      # - name: Wait for deploy to complete before progressing
-      #   uses: jakejarvis/wait-action@master
-      #   with:
-      #     time: '15m'
+          retention-days: 3
 
   build-mie-dev-us-west-2:
     runs-on: ubuntu-latest
@@ -94,7 +90,7 @@ jobs:
         with:
           name: templateUrl
           path: deployment/templateUrl.txt
-          retention-days: 1
+          retention-days: 3
   
 
   scan-3rd-party-data-us-west-2:
@@ -115,6 +111,8 @@ jobs:
             aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
             aws-region: us-west-2
 
+      # FIXME - need to identify what to scan for here - new entries in packages, 
+      # python dependencies, other copyrighted code ...
       - name: Get stack name
         run: |
           echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
@@ -123,10 +121,12 @@ jobs:
         run: |
           echo "TBD - scan for new 3rd party pacakges"
       
+      # FIXME - need to identify what to scan for here - is Trufflehog enough?
       - name: Scan for sensitive data
         run: |
-          echo "TBD - Scan for ensitive data"
+          echo "TBD - Scan for sensitive data"
       
+      # FIXME - need to make sure this is working properly
       # scan for various types of keys and tokens
       - name: Trufflehog Scan
         uses: edplato/trufflehog-actions-scan@master
@@ -161,9 +161,10 @@ jobs:
         with:
             input_path: deployment
   
+      # FIXME - This is not working.  Need to test more
       # check it with Hawkeye
-      - name: Hawkeye Scanner
-        uses: ./.github/actions/hawkeye-scan
+      # - name: Hawkeye Scanner
+      #   uses: ./.github/actions/hawkeye-scan
 
 
 
@@ -200,29 +201,32 @@ jobs:
           
           echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=true ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=true ParameterKey=EnableXrayTrace,ParameterValue=true --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
           aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=true ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=true ParameterKey=EnableXrayTrace,ParameterValue=true --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
-          if [[ $? -eq 0 ]]; then
-            CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
-            echo "Initial CREATE_STACK_STATUS is '$CREATE_STACK_STATUS'"
-            WAIT_TIME=0
-            while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
-            do
-              if [[ $WAIT_TIME -ge 1800 ]]; then
-                  echo "Deployment timed out after $WAIT_TIME seconds"
-                  exit 1
-              fi
-              echo "wait time is '$WAIT_TIME'"
-              ((WAIT_TIME=$WAIT_TIME+30))
-              sleep 30
-              CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
-              echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
-            done
-            echo "Stack creation stopped after $WAIT_TIME seconds"
-            if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
-              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
-              exit 1
-            fi
-            echo "Everything is awesome"
-          fi
+          # FIXME - this code is on probabtion.  Need to make sure it doesn't hang for many hours when 
+          # deployment fails as documentation is ambiguous - tested stack-delete-complete and it fails fast
+          aws cloudformation wait stack-create-complete --stack-name $MIE_STACK_NAME
+          # if [[ $? -eq 0 ]]; then
+          #   CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+          #   echo "Initial CREATE_STACK_STATUS is '$CREATE_STACK_STATUS'"
+          #   WAIT_TIME=0
+          #   while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
+          #   do
+          #     if [[ $WAIT_TIME -ge 1800 ]]; then
+          #         echo "Deployment timed out after $WAIT_TIME seconds"
+          #         exit 1
+          #     fi
+          #     echo "wait time is '$WAIT_TIME'"
+          #     ((WAIT_TIME=$WAIT_TIME+30))
+          #     sleep 30
+          #     CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+          #     echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+          #   done
+          #   echo "Stack creation stopped after $WAIT_TIME seconds"
+          #   if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
+          #     echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+          #     exit 1
+          #   fi
+          #   echo "Everything is awesome"
+          # fi
           echo "Everything is still awesome"
           exit 0
   
@@ -262,6 +266,8 @@ jobs:
           
           echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
           aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
+          # FIXME - this code is on probabtion.  Need to make sure it doesn't hang for many hours when 
+          # deployment fails as documentation is ambiguous - tested stack-delete-complete and it fails fast
           aws cloudformation wait stack-create-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
           # if [[ $? -eq 0 ]]; then
           #   CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
@@ -318,13 +324,15 @@ jobs:
         with:
             input_path: deployment
 
+      # FIXME - need unit tests
       # - name: Run unit tests
       #   run: |
       #     cd $GITHUB_WORKSPACE
       #     cd test/unit
       #     ./run_unit.sh workflowapi
       #     ./run_unit.sh dataplaneapi
-
+      
+      # FIXME - need integration tests
       # - name: Run integ tests
       #   run: |
       #     cd $GITHUB_WORKSPACE
