Remove deploy and aws credential steps from PR workflow

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -22,12 +22,12 @@ jobs:
         with:
           node-version: '16'
 
-      - name: Initialize AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-west-2
+      # - name: Initialize AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #     aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: us-west-2
 
       - name: Setup build environment
         run: |
@@ -70,12 +70,12 @@ jobs:
         with:
           node-version: '16'
 
-      - name: Initialize AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-west-2
+      # - name: Initialize AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #     aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: us-west-2
 
       - name: Generate short sha
         run: |
@@ -109,12 +109,12 @@ jobs:
         with:
           ref: ${{ github.sha }}
 
-      - name: Initialize test AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-            aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
-            aws-region: us-west-2
+      # - name: Initialize test AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #       aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
+      #       aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
+      #       aws-region: us-west-2
 
       # FIXME - need to identify what to scan for here - new entries in packages,
       # python dependencies, other copyrighted code ...
@@ -149,12 +149,12 @@ jobs:
         with:
           ref: ${{ github.sha }}
 
-      - name: Initialize test AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-            aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
-            aws-region: us-west-2
+      # - name: Initialize test AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #       aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
+      #       aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
+      #       aws-region: us-west-2
 
       - name: Generate short sha
         run: |
@@ -181,12 +181,12 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ github.sha }}
-      - name: Initialize build AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-            aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
-            aws-region: us-west-2
+      # - name: Initialize build AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #       aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+      #       aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+      #       aws-region: us-west-2
       - name: Generate short sha
         run: |
           echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
@@ -194,34 +194,34 @@ jobs:
           echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
       - name: Download all workflow run artifacts
         uses: actions/download-artifact@v2
-      - name: Deploy
-        run: |
-          EMAIL=${{ secrets.TEST_ADMIN_EMAIL }}
-          REGION=us-west-2
-          VERSION="pr-${SHORT_SHA}"
-          DIST_OUTPUT_BUCKET=micl-dev
-          TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
-          MIE_TEMPLATE=`cat templateUrl/templateUrl.txt`
+      # - name: Deploy
+      #   run: |
+      #     EMAIL=${{ secrets.TEST_ADMIN_EMAIL }}
+      #     REGION=us-west-2
+      #     VERSION="pr-${SHORT_SHA}"
+      #     DIST_OUTPUT_BUCKET=micl-dev
+      #     TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
+      #     MIE_TEMPLATE=`cat templateUrl/templateUrl.txt`
 
-          # Delete $MIE_STACK_NAME if it already exists.
-          # This is necessary in order to rerun github action workflows.
-          # If $MIE_STACK_NAME exists...
-          if [ $(echo $(aws cloudformation list-stacks --query 'StackSummaries[?StackName==`$MIE_STACK_NAME`]' --output text)  | tr -d '\n' | wc -c) > 0 ]; then
-            echo "Removing stack, $CONTENT_LOCALIZATION_STACK_NAME"
-            # Then delete $MIE_STACK_NAME, but first delete $CONTENT_LOCALIZATION_STACK_NAME since we can't delete $MIE_STACK_NAME until we've removed the dependent stack.
-            aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --region $REGION
-            aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
+      #     # Delete $MIE_STACK_NAME if it already exists.
+      #     # This is necessary in order to rerun github action workflows.
+      #     # If $MIE_STACK_NAME exists...
+      #     if [ $(echo $(aws cloudformation list-stacks --query 'StackSummaries[?StackName==`$MIE_STACK_NAME`]' --output text)  | tr -d '\n' | wc -c) > 0 ]; then
+      #       echo "Removing stack, $CONTENT_LOCALIZATION_STACK_NAME"
+      #       # Then delete $MIE_STACK_NAME, but first delete $CONTENT_LOCALIZATION_STACK_NAME since we can't delete $MIE_STACK_NAME until we've removed the dependent stack.
+      #       aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --region $REGION
+      #       aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
 
-            echo "Removing stack, $MIE_STACK_NAME"
-            aws cloudformation delete-stack --stack-name $MIE_STACK_NAME --region $REGION
-            aws cloudformation wait stack-delete-complete --stack-name $MIE_STACK_NAME
-          fi
+      #       echo "Removing stack, $MIE_STACK_NAME"
+      #       aws cloudformation delete-stack --stack-name $MIE_STACK_NAME --region $REGION
+      #       aws cloudformation wait stack-delete-complete --stack-name $MIE_STACK_NAME
+      #     fi
 
-          echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $MIE_TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=Yes ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=Yes ParameterKey=EnableXrayTrace,ParameterValue=Yes --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
+      #     echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $MIE_TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=Yes ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=Yes ParameterKey=EnableXrayTrace,ParameterValue=Yes --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
 
-          aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $MIE_TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=Yes ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=Yes ParameterKey=EnableXrayTrace,ParameterValue=Yes --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
-          aws cloudformation wait stack-create-complete --stack-name $MIE_STACK_NAME
-          exit 0
+      #     aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $MIE_TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=Yes ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=Yes ParameterKey=EnableXrayTrace,ParameterValue=Yes --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
+      #     aws cloudformation wait stack-create-complete --stack-name $MIE_STACK_NAME
+      #     exit 0
 
   deploy-content-localization-dev-us-west-2:
     needs:
@@ -237,12 +237,12 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ github.sha }}
-      - name: Initialize build AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-            aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
-            aws-region: us-west-2
+      # - name: Initialize build AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #       aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+      #       aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+      #       aws-region: us-west-2
       - name: Generate short sha
         run: |
           echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
@@ -250,36 +250,36 @@ jobs:
           echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
       - name: Download all workflow run artifacts
         uses: actions/download-artifact@v2
-      - name: Deploy
-        run: |
-          EMAIL=${{ secrets.TEST_ADMIN_EMAIL }}
-          REGION=us-west-2
-          VERSION="pr-${SHORT_SHA}"
-          DIST_OUTPUT_BUCKET=micl-dev
-          TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
-          CLO_TEMPLATE=`cat templateUrlMieDevelopment/template_url_that_uses_an_existing_mie_stack.txt`
+      # - name: Deploy
+      #   run: |
+      #     EMAIL=${{ secrets.TEST_ADMIN_EMAIL }}
+      #     REGION=us-west-2
+      #     VERSION="pr-${SHORT_SHA}"
+      #     DIST_OUTPUT_BUCKET=micl-dev
+      #     TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
+      #     CLO_TEMPLATE=`cat templateUrlMieDevelopment/template_url_that_uses_an_existing_mie_stack.txt`
 
-          # Delete $CONTENT_LOCALIZATION_STACK_NAME if it already exists.
-          # This is necessary in order to rerun github action workflows.
-          # If $CONTENT_LOCALIZATION_STACK_NAME exists...
-          if [ $(echo $(aws cloudformation list-stacks --query 'StackSummaries[?StackName==`$CONTENT_LOCALIZATION_STACK_NAME`]' --output text)  | tr -d '\n' | wc -c) > 0 ]; then
-            # Then delete $CONTENT_LOCALIZATION_STACK_NAME...
-            echo "Removing $CONTENT_LOCALIZATION_STACK_NAME so we can use that stack name again"
-            aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --region $REGION
-            aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-            if [ $? -ne 0 ]; then
-              # try once more if the wait failed
-              echo "Trying to remove $CONTENT_LOCALIZATION_STACK_NAME one more time"
-              aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --region $REGION
-              aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-            fi
-          fi
+      #     # Delete $CONTENT_LOCALIZATION_STACK_NAME if it already exists.
+      #     # This is necessary in order to rerun github action workflows.
+      #     # If $CONTENT_LOCALIZATION_STACK_NAME exists...
+      #     if [ $(echo $(aws cloudformation list-stacks --query 'StackSummaries[?StackName==`$CONTENT_LOCALIZATION_STACK_NAME`]' --output text)  | tr -d '\n' | wc -c) > 0 ]; then
+      #       # Then delete $CONTENT_LOCALIZATION_STACK_NAME...
+      #       echo "Removing $CONTENT_LOCALIZATION_STACK_NAME so we can use that stack name again"
+      #       aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --region $REGION
+      #       aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
+      #       if [ $? -ne 0 ]; then
+      #         # try once more if the wait failed
+      #         echo "Trying to remove $CONTENT_LOCALIZATION_STACK_NAME one more time"
+      #         aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --region $REGION
+      #         aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
+      #       fi
+      #     fi
 
-          echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLO_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
+      #     echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLO_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
 
-          aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLO_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
-          aws cloudformation wait stack-create-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-          exit 0
+      #     aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLO_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
+      #     aws cloudformation wait stack-create-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
+      #     exit 0
 
 
   test-content-localization-dev-us-west-2:
@@ -293,12 +293,12 @@ jobs:
         with:
           ref: ${{ github.sha }}
 
-      - name: Initialize test AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-            aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
-            aws-region: us-west-2
+      # - name: Initialize test AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #       aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
+      #       aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
+      #       aws-region: us-west-2
 
       - name: Generate short sha
         run: |
@@ -319,16 +319,16 @@ jobs:
       #     ./run_unit.sh workflowapi
       #     ./run_unit.sh dataplaneapi
 
-      - name: Initialize build AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-west-2
+      # - name: Initialize build AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #     aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: us-west-2
 
-      - name: Delete stack
-        run: |
-          aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-          aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-          aws cloudformation delete-stack --stack-name $MIE_STACK_NAME
-          aws cloudformation wait stack-delete-complete --stack-name $MIE_STACK_NAME
+      # - name: Delete stack
+      #   run: |
+      #     aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME
+      #     aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
+      #     aws cloudformation delete-stack --stack-name $MIE_STACK_NAME
+      #     aws cloudformation wait stack-delete-complete --stack-name $MIE_STACK_NAME
