bs

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -102,11 +102,14 @@ jobs:
             fi
             echo "wait time is '$WAIT_TIME'"
             ((WAIT_TIME=$WAIT_TIME+30))
-            echo "wait time is '$WAIT_TIME'"
             sleep 30
-            echo "slept"
             CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
             echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            echo "Stack creation stopped after $WAIT_TIME seconds"
+            if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
+              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+              exit 1
+            echo "Everything is awesome"
           fi
           echo "????"
           exit 0
