build mie

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -57,6 +57,44 @@ jobs:
       #   with:
       #     time: '15m'
 
+  build-mie-dev-us-west-2:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout MIE development branch
+        uses: actions/checkout@v2
+        with:
+          repository: awslabs/aws-media-insights-engine
+          ref: development
+
+      - name: Initialize AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-west-2
+
+      - name: Generate short sha
+        run: |
+          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
+
+      - name: Run build script
+        run: |
+          cd deployment
+          MIE_STACK_NAME="pr${SHORT_SHA}"
+          REGION=us-west-2
+          VERSION="pr${SHORT_SHA}"
+          DIST_OUTPUT_BUCKET=mie-dev
+          TEMPLATE_OUTPUT_BUCKET=mie-dev-us-west-2
+          ./build-s3-dist.sh --no-layer --template-bucket $TEMPLATE_OUTPUT_BUCKET --code-bucket $DIST_OUTPUT_BUCKET --version $VERSION --region $REGION
+          read -r TEMPLATE < templateUrl.txt
+          pwd
+
+      - name: 'Upload MIE One-click Deployment Artifact'
+        uses: actions/upload-artifact@v2
+        with:
+          name: templateUrl
+          path: deployment/templateUrl.txt
+          retention-days: 1
   
   scan-3rd-party-data-us-west-2:
     needs: build-us-west-2
@@ -76,7 +114,7 @@ jobs:
             aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
             aws-region: us-west-2
 
-      - name: Generate short sha
+      - name: Get stack name
         run: |
           echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
 
@@ -164,6 +202,65 @@ jobs:
               ((WAIT_TIME=$WAIT_TIME+30))
               sleep 30
               CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+              echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            done
+            echo "Stack creation stopped after $WAIT_TIME seconds"
+            if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
+              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+              exit 1
+            fi
+            echo "Everything is awesome"
+          fi
+          echo "Everything is still awesome"
+          exit 0
+
+  deploy-mie-dev-us-west-2:
+    needs: build-mie-dev-us-west-2
+    runs-on: ubuntu-latest
+    env:
+      MIE_REGION: 'us-west-2'
+    steps:
+      - name: Check out pr branch
+        uses: actions/checkout@v2.3.4
+        with:
+          ref: ${{ github.sha }}
+      - name: Initialize build AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+            aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+            aws-region: us-west-2
+      - name: Generate short sha
+        run: |
+          echo "MIE_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
+          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
+      - name: Download all workflow run artifacts
+        uses: actions/download-artifact@v2
+      - name: Deploy
+        run: |
+          EMAIL=micontentlocalization@gmail.com
+          REGION=us-west-2
+          VERSION="pr-${SHORT_SHA}"
+          DIST_OUTPUT_BUCKET=micl-dev
+          TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
+          TEMPLATE=`cat templateUrl/templateUrl.txt`
+          
+          echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=true ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=true ParameterKey=EnableXrayTrace,ParameterValue=true --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
+          aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=true ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=true ParameterKey=EnableXrayTrace,ParameterValue=true --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
+          if [[ $? -eq 0 ]]; then
+            CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+            echo "Initial CREATE_STACK_STATUS is '$CREATE_STACK_STATUS'"
+            WAIT_TIME=0
+            while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
+            do
+              if [[ $WAIT_TIME -ge 1800 ]]; then
+                  echo "Deployment timed out after $WAIT_TIME seconds"
+                  exit 1
+              fi
+              echo "wait time is '$WAIT_TIME'"
+              ((WAIT_TIME=$WAIT_TIME+30))
+              sleep 30
+              CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CMIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
               echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
             done
             echo "Stack creation stopped after $WAIT_TIME seconds"
