check deploy status in loop

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -43,23 +43,28 @@ jobs:
           aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
           echo "wait for deploy to complete"
           if [[ $? -eq 0 ]]; then
-            # Wait for create-stack to finish
             echo  "Waiting for create-stack command to complete"
             CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
-            echo "CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
-            WAIT_TIME=0
-                # Timeout check - 15 min
-                if [[ $WAIT_TIME -ge 900 ]]; then
-                    echo "Deployment timed out after $WAIT_TIME seconds"
-                    exit 1
-                fi
-                ((WAIT_TIME=$WAIT_TIME+30))
-                echo "WAIT_TIME = $WAIT_TIME"
-                sleep 30
-                CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
-                echo "CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            echo "Initial CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            ((WAIT_TIME=0))
+            while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
+            do
+              # Timeout check - 15 min
+              if [[ $WAIT_TIME -ge 900 ]]; then
+                  echo "Deployment timed out after $WAIT_TIME seconds"
+                  exit 1
+              fi
+              ((WAIT_TIME=$WAIT_TIME+30))
+              sleep 30
+              CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+              echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            done
+            echo "Stack creation stopped after $WAIT_TIME seconds"
+            if [[$CREATE_STACK_STATUS != "CREATE_COMPLETE"]]; then 
+              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+              exit 1
           fi
-          echo "check the status of the deployment"
+          exit 0
 
 
       - name: Wait for deploy to complete before progressing
