Don't fail the release-workflow if staging branch already exists but do fail the release-workflow if the release branch already exists because we don't want to accidentally overwrite a previous release.

diff --git a/.github/workflows/release-workflow.yml b/.github/workflows/release-workflow.yml
--- a/.github/workflows/release-workflow.yml
+++ b/.github/workflows/release-workflow.yml
@@ -20,7 +20,9 @@ jobs:
           ref: development
       - name: Create release branch
         run: |
-          git push origin --delete release/v${{ github.event.inputs.version }}
+          echo "Creating release/v${{ github.event.inputs.version }} branch"
+          git branch -r | grep release/v${{ github.event.inputs.version }}
+          if [ $? -eq 0 ]; then echo "This workflow will now fail because the release/v${{ github.event.inputs.version }} branch already exists. Remove it then run this workflow again."; fi
           git checkout -b release/v${{ github.event.inputs.version }}
       - name: Initialize mandatory git config
         run: |
@@ -750,7 +752,10 @@ jobs:
           ref: main
       - name: Create staging branch
         run: |
+          git branch -r | grep staging/v${{ github.event.inputs.version }}
+          if [ $? -eq 0 ]; then echo "Branch staging/v${{ github.event.inputs.version }} already exists. Deleting it now..."; fi
           git push origin --delete staging/v${{ github.event.inputs.version }}
+          echo "Creating staging/v${{ github.event.inputs.version }} branch"
           git checkout -b staging/v${{ github.event.inputs.version }}
       - name: Initialize mandatory git config
         run: |
