release and scheduled workflows

diff --git a/.github/workflows/release-workflow.yml b/.github/workflows/release-workflow.yml
--- a/.github/workflows/release-workflow.yml
+++ b/.github/workflows/release-workflow.yml
@@ -1,12 +1,18 @@
-name: scheduled-workflow
+name: release-workflow
 
 on:
-  schedule:
-    - cron: '0 4 * * *'
+  workflow_dispatch:
+    inputs:
+        version:
+          description: 'Version number of release (e.g. 2.1.0)'
+          required: true
+        releaseName:
+          description: 'Name of the release (e.g. Nautilus)'
+          required: true
 
 jobs:
   # Build and new deploy based on latest release of MIE
-  build-content-localization-dev-us-west-2:
+  build-us-west-2:
     runs-on: ubuntu-latest
     steps:
       - name: Check out pr branch
@@ -43,13 +49,17 @@ jobs:
         with:
           name: templateUrlMieRelease
           path: src/templateUrlMieRelease.txt
-          retention-days: 3
+          retention-days: 1
       - name: 'Upload Developer Deployment Artifact'
         uses: actions/upload-artifact@v2
         with:
           name: templateUrlMieDevelopment
           path: src/templateUrlMieDevelopment.txt
-          retention-days: 3
+          retention-days: 1
+      # - name: Wait for deploy to complete before progressing
+      #   uses: jakejarvis/wait-action@master
+      #   with:
+      #     time: '15m'
 
   build-mie-dev-us-west-2:
     runs-on: ubuntu-latest
@@ -88,11 +98,11 @@ jobs:
         with:
           name: templateUrl
           path: deployment/templateUrl.txt
-          retention-days: 3
+          retention-days: 1
   
 
   scan-3rd-party-data-us-west-2:
-    needs: build-content-localization-dev-us-west-2
+    needs: build-us-west-2
     runs-on: ubuntu-latest
     env:
       MIE_REGION: 'us-west-2'
@@ -109,8 +119,6 @@ jobs:
             aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
             aws-region: us-west-2
 
-      # FIXME - need to identify what to scan for here - new entries in packages, 
-      # python dependencies, other copyrighted code ...
       - name: Get stack name
         run: |
           echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
@@ -119,20 +127,12 @@ jobs:
         run: |
           echo "TBD - scan for new 3rd party pacakges"
       
-      # FIXME - need to identify what to scan for here - is Trufflehog enough?
       - name: Scan for sensitive data
         run: |
-          echo "TBD - Scan for sensitive data"
-
-      # FIXME - need to make sure this is working properly
-      # scan for various types of keys and tokens
-      - name: Trufflehog Scan
-        uses: edplato/trufflehog-actions-scan@master
-        with:
-          scanArguments: '--regex --entropy=False'   
+          echo "TBD - Scan for ensitive data"
 
   scan-us-west-2:
-    needs: build-content-localization-dev-us-west-2
+    needs: build-us-west-2
     runs-on: ubuntu-latest
     env:
       MIE_REGION: 'us-west-2'
@@ -159,10 +159,66 @@ jobs:
         with:
             input_path: deployment
 
-      #FIXME - This is not working.  Need to test more
-      # check it with Hawkeye
-      # - name: Hawkeye Scanner
-      #   uses: ./.github/actions/hawkeye-scan
+  deploy-us-west-2:
+    needs: build-us-west-2
+    runs-on: ubuntu-latest
+    env:
+      MIE_REGION: 'us-west-2'
+    steps:
+      - name: Check out pr branch
+        uses: actions/checkout@v2.3.4
+        with:
+          ref: ${{ github.sha }}
+
+      - name: Initialize build AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+            aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+            aws-region: us-west-2
+      - name: Generate short sha
+        run: |
+          echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
+          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
+      - name: Download all workflow run artifacts
+        uses: actions/download-artifact@v2
+      - name: Deploy
+        run: |
+          EMAIL=micontentlocalization@gmail.com
+          REGION=us-west-2
+          VERSION="pr-${SHORT_SHA}"
+          DIST_OUTPUT_BUCKET=micl-dev
+          TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
+          CLOUDFORMATION_TEMPLATE=`cat templateUrlMieRelease/templateUrlMieRelease.txt`
+          
+          echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
+          aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
+          if [[ $? -eq 0 ]]; then
+            CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+            echo "Initial CREATE_STACK_STATUS is '$CREATE_STACK_STATUS'"
+            WAIT_TIME=0
+            while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
+            do
+              if [[ $WAIT_TIME -ge 1800 ]]; then
+                  echo "Deployment timed out after $WAIT_TIME seconds"
+                  exit 1
+              fi
+              echo "wait time is '$WAIT_TIME'"
+              ((WAIT_TIME=$WAIT_TIME+30))
+              sleep 30
+              CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+              echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            done
+            echo "Stack creation stopped after $WAIT_TIME seconds"
+            if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
+              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+              exit 1
+            fi
+            echo "Everything is awesome"
+          fi
+          echo "Everything is still awesome"
+          exit 0
+
   deploy-mie-dev-us-west-2:
     needs: build-mie-dev-us-west-2
     runs-on: ubuntu-latest
@@ -196,13 +252,34 @@ jobs:
           
           echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=true ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=true ParameterKey=EnableXrayTrace,ParameterValue=true --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
           aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=true ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=true ParameterKey=EnableXrayTrace,ParameterValue=true --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
-          aws cloudformation wait stack-create-complete --stack-name $MIE_STACK_NAME
+          if [[ $? -eq 0 ]]; then
+            CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+            echo "Initial CREATE_STACK_STATUS is '$CREATE_STACK_STATUS'"
+            WAIT_TIME=0
+            while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
+            do
+              if [[ $WAIT_TIME -ge 1800 ]]; then
+                  echo "Deployment timed out after $WAIT_TIME seconds"
+                  exit 1
+              fi
+              echo "wait time is '$WAIT_TIME'"
+              ((WAIT_TIME=$WAIT_TIME+30))
+              sleep 30
+              CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CMIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+              echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            done
+            echo "Stack creation stopped after $WAIT_TIME seconds"
+            if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
+              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+              exit 1
+            fi
+            echo "Everything is awesome"
+          fi
+          echo "Everything is still awesome"
           exit 0
   
   deploy-content-localization-dev-us-west-2:
-    needs: 
-      - deploy-mie-dev-us-west-2
-      - build-content-localization-dev-us-west-2
+    needs: deploy-mie-dev-us-west-2
     runs-on: ubuntu-latest
     env:
       MIE_REGION: 'us-west-2'
@@ -235,11 +312,34 @@ jobs:
           
           echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
           aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch ParameterKey=MieStackName,ParameterValue=$MIE_STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
-          aws cloudformation wait stack-create-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
+          if [[ $? -eq 0 ]]; then
+            CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${MIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+            echo "Initial CREATE_STACK_STATUS is '$CREATE_STACK_STATUS'"
+            WAIT_TIME=0
+            while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
+            do
+              if [[ $WAIT_TIME -ge 1800 ]]; then
+                  echo "Deployment timed out after $WAIT_TIME seconds"
+                  exit 1
+              fi
+              echo "wait time is '$WAIT_TIME'"
+              ((WAIT_TIME=$WAIT_TIME+30))
+              sleep 30
+              CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CMIE_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+              echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            done
+            echo "Stack creation stopped after $WAIT_TIME seconds"
+            if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
+              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+              exit 1
+            fi
+            echo "Everything is awesome"
+          fi
+          echo "Everything is still awesome"
           exit 0
 
-  test-content-localization-dev-us-west-2:
-    needs: deploy-content-localization-dev-us-west-2
+  test-us-west-2:
+    needs: deploy-us-west-2
     runs-on: ubuntu-latest
     env:
       MIE_REGION: 'us-west-2'
@@ -259,7 +359,6 @@ jobs:
       - name: Generate short sha
         run: |
           echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
-          echo "MIE_STACK_NAME=prmie`git rev-parse --short HEAD`" >> $GITHUB_ENV
 
       - name: Run cfn_nag
         uses: stelligent/cfn_nag@master
@@ -290,6 +389,3 @@ jobs:
       - name: Delete stack
         run: |
           aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-          aws cloudformation wait stack-delete-complete --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-          aws cloudformation delete-stack --stack-name $MIE_STACK_NAME
-          aws cloudformation wait stack-delete-complete --stack-name $MIE_STACK_NAME
