scheduled workflow

diff --git a/.github/workflows/scheduled-workflow.yml b/.github/workflows/scheduled-workflow.yml
--- a/.github/workflows/scheduled-workflow.yml
+++ b/.github/workflows/scheduled-workflow.yml
@@ -1,10 +1,8 @@
-name: pr-workflow
+name: scheduled-workflow
 
 on:
-  pull_request:
-    types: [opened, synchronize]
-    branches:
-      - development
+  schedule:
+    - cron: '0 4 * * *'
 
 jobs:
   # Build and new deploy based on latest release of MIE
@@ -155,6 +153,66 @@ jobs:
         with:
             input_path: deployment
 
+  deploy-us-west-2:
+    needs: build-us-west-2
+    runs-on: ubuntu-latest
+    env:
+      MIE_REGION: 'us-west-2'
+    steps:
+      - name: Check out pr branch
+        uses: actions/checkout@v2.3.4
+        with:
+          ref: ${{ github.sha }}
+
+      - name: Initialize build AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+            aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
+            aws-region: us-west-2
+      - name: Generate short sha
+        run: |
+          echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
+          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
+      - name: Download all workflow run artifacts
+        uses: actions/download-artifact@v2
+      - name: Deploy
+        run: |
+          EMAIL=micontentlocalization@gmail.com
+          REGION=us-west-2
+          VERSION="pr-${SHORT_SHA}"
+          DIST_OUTPUT_BUCKET=micl-dev
+          TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
+          CLOUDFORMATION_TEMPLATE=`cat templateUrlMieRelease/templateUrlMieRelease.txt`
+          
+          echo "deploy cloudformation: 'aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback'"
+          aws cloudformation create-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME --template-url $CLOUDFORMATION_TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL ParameterKey=ElasticSearchNodeSize,ParameterValue=t2.small.elasticsearch --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
+          if [[ $? -eq 0 ]]; then
+            CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+            echo "Initial CREATE_STACK_STATUS is '$CREATE_STACK_STATUS'"
+            WAIT_TIME=0
+            while [[ $CREATE_STACK_STATUS == "REVIEW_IN_PROGRESS" ]] || [[ $CREATE_STACK_STATUS == "CREATE_IN_PROGRESS" ]] 
+            do
+              if [[ $WAIT_TIME -ge 1800 ]]; then
+                  echo "Deployment timed out after $WAIT_TIME seconds"
+                  exit 1
+              fi
+              echo "wait time is '$WAIT_TIME'"
+              ((WAIT_TIME=$WAIT_TIME+30))
+              sleep 30
+              CREATE_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${CONTENT_LOCALIZATION_STACK_NAME} --region ${AWS_REGION} --query 'Stacks[0].StackStatus' --output text)
+              echo "At $WAIT_TIME seconds CREATE_STACK_STATUS is $CREATE_STACK_STATUS"
+            done
+            echo "Stack creation stopped after $WAIT_TIME seconds"
+            if [[ $CREATE_STACK_STATUS != "CREATE_COMPLETE" ]]; then 
+              echo "Stack creation FAILED with status $CREATE_STACK_STATUS"
+              exit 1
+            fi
+            echo "Everything is awesome"
+          fi
+          echo "Everything is still awesome"
+          exit 0
+
   deploy-mie-dev-us-west-2:
     needs: build-mie-dev-us-west-2
     runs-on: ubuntu-latest
@@ -274,8 +332,8 @@ jobs:
           echo "Everything is still awesome"
           exit 0
 
-  test-content-localization-dev-us-west-2:
-    needs: deploy-content-localization-dev-us-west-2
+  test-us-west-2:
+    needs: deploy-us-west-2
     runs-on: ubuntu-latest
     env:
       MIE_REGION: 'us-west-2'
@@ -295,7 +353,6 @@ jobs:
       - name: Generate short sha
         run: |
           echo "CONTENT_LOCALIZATION_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
-          echo "MIE_STACK_NAME=prmie`git rev-parse --short HEAD`" >> $GITHUB_ENV
 
       - name: Run cfn_nag
         uses: stelligent/cfn_nag@master
@@ -326,6 +383,3 @@ jobs:
       - name: Delete stack
         run: |
           aws cloudformation delete-stack --stack-name $CONTENT_LOCALIZATION_STACK_NAME
-          sleep 1200
-          aws cloudformation delete-stack --stack-name $MIE_STACK_NAME
-
